# Generated by Django 2.0 on 2018-05-20 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(choices=[('A', 'Ace'), ('K', 'King'), ('Q', 'Queen'), ('J', 'Jack'), ('10', 'Ten'), ('9', 'Nine'), ('8', 'Eight'), ('7', 'Seven'), ('6', 'Six'), ('5', 'Five'), ('4', 'Four'), ('3', 'Three'), ('2', 'Two')], max_length=2)),
                ('suit', models.CharField(choices=[('CB', 'Club'), ('SP', 'Spade'), ('HT', 'Heart'), ('DM', 'Diamond')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='dealer_hand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_hand', to='game.Hand'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_hand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_hand', to='game.Hand'),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='hand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Hand'),
        ),
    ]
