# Generated by Django 2.0 on 2018-05-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bet',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
