# Generated by Django 2.0 on 2018-05-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20180522_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='is_deck',
            field=models.BooleanField(default=False),
        ),
    ]
