# Generated by Django 2.0 on 2018-05-23 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_hand_is_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_doubled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='has_insured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player_split_hand',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_split_hand', to='game.Hand'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_finished',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='time_started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
