# Generated by Django 2.0 on 2018-05-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20180523_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='standing',
            field=models.NullBooleanField(default=False),
        ),
    ]
